//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.LICHSUTHEMDICHVUs = new HashSet<LICHSUTHEMDICHVU>();
        }
    
        public string DichVuID { get; set; }
        public string TenDichVu { get; set; }
        public double GiaBan { get; set; }
        public double GiaCungCap { get; set; }
        public bool TinhTrangTonTai { get; set; }
        public string LoaiDVID { get; set; }
        public string DonVi { get; set; }
        public System.DateTime NgayTao { get; set; }
        public byte[] HinhAnh { get; set; }
    
        public virtual LOAIDV LOAIDV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUTHEMDICHVU> LICHSUTHEMDICHVUs { get; set; }
    }
}
