//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.HOADONTHUEPHONGs = new HashSet<HOADONTHUEPHONG>();
        }
    
        public int MaKH { get; set; }
        public string HoTen { get; set; }
        public decimal SDT { get; set; }
        public string DiaChi { get; set; }
        public decimal CMND { get; set; }
        public bool TinhTrang { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<HOADONTHUEPHONG> HOADONTHUEPHONGs { get; set; }
    }
}
