//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIDV
    {
        public LOAIDV()
        {
            this.DICHVUs = new HashSet<DICHVU>();
        }
    
        public string LoaiDVID { get; set; }
        public string TenLoai { get; set; }
        public bool TinhTrang { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<DICHVU> DICHVUs { get; set; }
    }
}
