//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSTHONGBAO
    {
        public int LSThongBaoID { get; set; }
        public string DanhSachNhan { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<System.DateTime> NgayTB { get; set; }
    }
}
