//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachSan.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKHACHSANEntities : DbContext
    {
        public QLKHACHSANEntities()
            : base("name=QLKHACHSANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BANGTHAMSO> BANGTHAMSOes { get; set; }
        public DbSet<DICHVU> DICHVUs { get; set; }
        public DbSet<HOADONTHUEPHONG> HOADONTHUEPHONGs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LICHSUTHEMDICHVU> LICHSUTHEMDICHVUs { get; set; }
        public DbSet<LOAIDV> LOAIDVs { get; set; }
        public DbSet<LOAINHANVIEN> LOAINHANVIENs { get; set; }
        public DbSet<LOAIPHONG> LOAIPHONGs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<NVKETOAN> NVKETOANs { get; set; }
        public DbSet<NVLETAN> NVLETANs { get; set; }
        public DbSet<NVQUANLI> NVQUANLIs { get; set; }
        public DbSet<PHONG> PHONGs { get; set; }
    }
}
