//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.HOADONTHUEPHONGs = new HashSet<HOADONTHUEPHONG>();
        }
    
        public string PhongID { get; set; }
        public string TenPhong { get; set; }
        public double DonGia { get; set; }
        public bool TinhTrangTonTai { get; set; }
        public bool TinhTrangThue { get; set; }
        public string LoaiPhongID { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONTHUEPHONG> HOADONTHUEPHONGs { get; set; }
        public virtual LOAIPHONG LOAIPHONG { get; set; }
    }
}
