USE MASTER
GO
IF DB_ID('QLKHACHSAN') IS NOT NULL
	DROP DATABASE QLKHACHSAN
GO
GO
CREATE DATABASE QLKHACHSAN
GO
USE QLKHACHSAN
GO

CREATE TABLE HASTAG(
	HastagID int IDENTITY(1,1) NOT NULL,
	Name nvarchar(50) NOT NULL
	CONSTRAINT PK_HASTAG PRIMARY KEY CLUSTERED (HastagID ASC))

GO

CREATE TABLE THONGTINDANGKI(
	MaDangKi int IDENTITY(1,1) NOT NULL,
	HastagID int NOT NULL,
	NhanVienID int NOT NULL,
	NgayDangKi datetime NOT NULL
	CONSTRAINT PK_MaDangKi PRIMARY KEY CLUSTERED (MaDangKi ASC))
GO







CREATE TABLE HOADONTHUEPHONG(
	MaHoaDon int IDENTITY(1,1) NOT NULL,
	ThoiGianThue datetime NOT NULL,
	ThoiGianTra datetime NULL,
	TongTien float NULL,
	NhanVienTaoHoaDon int NOT NULL,
	Phong varchar(10) NOT NULL,
	MaKhachHang int NOT NULL,
	NgayTao datetime NOT NULL CONSTRAINT DF_HOADONTHUEPHONG_NgayTao  DEFAULT (getdate()),
	CONSTRAINT PK_HOADONTHUEPHONG PRIMARY KEY CLUSTERED (MaHoaDon ASC))
GO
CREATE TABLE KHACHHANG(
	MaKH int IDENTITY(1,1) NOT NULL,
	HoTen nvarchar(100) NOT NULL,
	SDT numeric(10, 0) NOT NULL,
	DiaChi nvarchar(200) NULL,
	CMND numeric(15, 0) NOT NULL,
	TinhTrang bit NOT NULL,
	NgayTao datetime NOT NULL CONSTRAINT DF_KHACHHANG_NgayTao  DEFAULT (getdate()),
	CONSTRAINT PK_KHACHHANG 
	PRIMARY KEY CLUSTERED (MaKH ASC)
)

GO

CREATE TABLE LICHSUTHEMDICHVU(
	ThoiGianThem datetime NOT NULL CONSTRAINT DF_LICHSUTHEMDICHVU_ThoiGianthem  DEFAULT (getdate()),
	SoLuong int NOT NULL,
	MaHoaDon int NOT NULL,
	DichVuID varchar(10) NOT NULL,
	CONSTRAINT PK_LICHSUTHEMDICHVU 
	PRIMARY KEY CLUSTERED 
	(
	ThoiGianThem ASC,
	MaHoaDon ASC,
	DichVuID ASC
	)
)

GO

CREATE TABLE LOAIDV(
	LoaiDVID varchar(10) NOT NULL,
	TenLoai nvarchar(200) NOT NULL,
	TinhTrang bit NOT NULL,
	NgayTao datetime NOT NULL
	CONSTRAINT DF_LOAIDV_NgayTao  DEFAULT (getdate()),
	CONSTRAINT PK_LOAIDV 
	PRIMARY KEY CLUSTERED (LoaiDVID ASC))


GO
CREATE TABLE DICHVU(
	DichVuID varchar(10) NOT NULL,
	TenDichVu nvarchar(200) NOT NULL,
	GiaBan float NOT NULL,
	GiaCungCap float NOT NULL,
	TinhTrangTonTai bit NOT NULL,
	LoaiDVID varchar(10) NOT NULL,
	DonVi nvarchar(50) NULL,
	NgayTao datetime NOT NULL
	CONSTRAINT DF_DICHVU_NgayTao  DEFAULT (getdate()),
	CONSTRAINT PK_DICHVU 
	PRIMARY KEY (DichVuID ASC))
go
CREATE TABLE LOAIPHONG(
	LoaiPhongID varchar(10) NOT NULL,
	TenLoai nvarchar(200) NOT NULL,
	TinhTrang bit NOT NULL,
	NgayTao datetime NOT NULL
	CONSTRAINT DF_LOAIPHONG_NgayTao  DEFAULT (getdate()),
	 CONSTRAINT PK_LOAIPHONG 
	 PRIMARY KEY CLUSTERED (LoaiPhongID ASC)
)
GO
CREATE TABLE PHONG(
	PhongID varchar(10) NOT NULL,
	TenPhong nvarchar(200) NOT NULL,
	DonGia float NOT NULL,
	TinhTrangTonTai bit NOT NULL,
	TinhTrangThue bit NOT NULL,
	LoaiPhongID varchar(10) NOT NULL,
	NgayTao datetime NOT NULL
	CONSTRAINT DF_PHONG_NgayTao  DEFAULT (getdate()),
	 CONSTRAINT PK_PHONG 
	 PRIMARY KEY CLUSTERED (PhongID ASC)
)
GO
CREATE TABLE LOAINHANVIEN(
	LoaiNVID int NOT NULL,
	TenLoai nvarchar(200) NOT NULL,
	TinhTrang bit NOT NULL,
	NgayTao datetime NOT NULL
	CONSTRAINT FK_LOAINV_NgayTao  DEFAULT (getdate()),
	CONSTRAINT PK_LoaiNV 
	PRIMARY KEY CLUSTERED (LoaiNVID ASC))

GO
ALTER TABLE LOAINHANVIEN ADD  CONSTRAINT DF_LOAINV_TinhTrang  DEFAULT ((0)) FOR TinhTrang
GO
CREATE TABLE NHANVIEN(
	NhanVienID int IDENTITY(1,1) NOT NULL,
	TenDangNhap varchar(50) NOT NULL,
	MatKhau varchar(100) NOT NULL,
	TinhTrang bit NOT NULL,
	HoTen nvarchar(100) NOT NULL,
	DiaChi nvarchar(200) NOT NULL,
	NgaySinh date NOT NULL,
	SDT numeric(10, 0) NOT NULL,
	CMND numeric(15, 0) NOT NULL,
	Email varchar(50) NULL,
	Loai int NOT NULL,
	NgayTao datetime NOT NULL
	CONSTRAINT DF_NHANVIEN_NgayTao  DEFAULT (getdate()),
	CONSTRAINT PK_NHANVIEN 
	PRIMARY KEY CLUSTERED (NhanVienID ASC)
)

GO

CREATE TABLE NVKETOAN(
	NhanVienID int NOT NULL,
	 CONSTRAINT PK_NVKETOAN PRIMARY KEY CLUSTERED(NhanVienID ASC)
)

GO
CREATE TABLE NVLETAN(
	NhanVienID int NOT NULL,
	CONSTRAINT PK_NVLETAN 
	PRIMARY KEY CLUSTERED (NhanVienID ASC)
)

GO
CREATE TABLE NVQUANLI(
	NhanVienID int NOT NULL,
	CONSTRAINT PK_NVQUANLI 
	PRIMARY KEY CLUSTERED (NhanVienID ASC)
)
CREATE TABLE BANGTHAMSO(
	MaThamSo varchar(50) NOT NULL,
	TenThamSo nvarchar(200) NOT NULL,
	TinhTrang bit NOT NULL,
	KieuDuLieu varchar(200) NOT NULL,
	GiaTri varchar(200) NOT NULL,
	NgayTao datetime NOT NULL
	CONSTRAINT FK_BANGTHAMSO_NgayTao  DEFAULT (getdate()),
	CONSTRAINT PK_BANGTHAMSO 
	PRIMARY KEY CLUSTERED (MaThamSo ASC))
ALTER TABLE BANGTHAMSO ADD  CONSTRAINT DF_BANGTHAMSO_TinhTrang  DEFAULT ((0)) FOR TinhTrang
GO
-- set default value tinhTrang=0-> chua xoa
ALTER TABLE DICHVU ADD  CONSTRAINT DF_DICHVU_TinhTrangTonTai  DEFAULT ((0)) FOR TinhTrangTonTai

GO
ALTER TABLE KHACHHANG ADD  CONSTRAINT DF_KHACHHANG_TinhTrang  DEFAULT ((0)) FOR TinhTrang
GO
ALTER TABLE LOAIDV ADD  CONSTRAINT DF_LOAIDV_TinhTrang  DEFAULT ((0)) FOR TinhTrang
GO
ALTER TABLE LOAIPHONG ADD  CONSTRAINT DF_LOAIPHONG_TinhTrang  DEFAULT ((0)) FOR TinhTrang
GO
ALTER TABLE NHANVIEN ADD  CONSTRAINT DF_NHANVIEN_TinhTrang  DEFAULT ((0)) FOR TinhTrang
GO
ALTER TABLE PHONG ADD  CONSTRAINT DF_PHONG_TinhTrangTonTai  DEFAULT ((0)) FOR TinhTrangTonTai
GO
ALTER TABLE PHONG ADD  CONSTRAINT DF_PHONG_TinhTrangThue  DEFAULT ((0)) FOR TinhTrangThue
GO
--Khoa Ngoai
ALTER TABLE DICHVU  WITH CHECK ADD  CONSTRAINT FK_DICHVU_LOAIDV FOREIGN KEY(LoaiDVID)
REFERENCES LOAIDV (LoaiDVID)
GO
ALTER TABLE DICHVU CHECK CONSTRAINT FK_DICHVU_LOAIDV
GO
ALTER TABLE HOADONTHUEPHONG  WITH CHECK ADD  CONSTRAINT FK_HOADONTHUEPHONG_KHACHHANG FOREIGN KEY(MaKhachHang)
REFERENCES KHACHHANG (MaKH)
GO
ALTER TABLE HOADONTHUEPHONG CHECK CONSTRAINT FK_HOADONTHUEPHONG_KHACHHANG
GO
ALTER TABLE HOADONTHUEPHONG  WITH CHECK ADD  CONSTRAINT FK_HOADONTHUEPHONG_NHANVIEN FOREIGN KEY(NhanVienTaoHoaDon)
REFERENCES NHANVIEN (NhanVienID)
GO
ALTER TABLE HOADONTHUEPHONG CHECK CONSTRAINT FK_HOADONTHUEPHONG_NHANVIEN
GO
ALTER TABLE HOADONTHUEPHONG  WITH CHECK ADD  CONSTRAINT FK_HOADONTHUEPHONG_PHONG FOREIGN KEY(Phong)
REFERENCES PHONG (PhongID)
GO
ALTER TABLE HOADONTHUEPHONG CHECK CONSTRAINT FK_HOADONTHUEPHONG_PHONG
GO
ALTER TABLE LICHSUTHEMDICHVU  WITH CHECK ADD  CONSTRAINT FK_LICHSUTHEMDICHVU_DICHVU FOREIGN KEY(DichVuID)
REFERENCES DICHVU (DichVuID)
GO
ALTER TABLE LICHSUTHEMDICHVU CHECK CONSTRAINT FK_LICHSUTHEMDICHVU_DICHVU
GO
ALTER TABLE LICHSUTHEMDICHVU  WITH CHECK ADD  CONSTRAINT FK_LICHSUTHEMDICHVU_HOADONTHUEPHONG FOREIGN KEY(MaHoaDon)
REFERENCES HOADONTHUEPHONG (MaHoaDon)
GO
ALTER TABLE LICHSUTHEMDICHVU CHECK CONSTRAINT FK_LICHSUTHEMDICHVU_HOADONTHUEPHONG
GO
ALTER TABLE NVKETOAN  WITH CHECK ADD  CONSTRAINT FK_NVKETOAN_NHANVIEN FOREIGN KEY(NhanVienID)
REFERENCES NHANVIEN (NhanVienID)
GO
ALTER TABLE NVKETOAN CHECK CONSTRAINT FK_NVKETOAN_NHANVIEN
GO
ALTER TABLE NVLETAN  WITH CHECK ADD  CONSTRAINT FK_NVLETAN_NHANVIEN FOREIGN KEY(NhanVienID)
REFERENCES NHANVIEN (NhanVienID)
GO
ALTER TABLE NVLETAN CHECK CONSTRAINT FK_NVLETAN_NHANVIEN
GO
ALTER TABLE NVQUANLI  WITH CHECK ADD  CONSTRAINT FK_NVQUANLI_NHANVIEN FOREIGN KEY(NhanVienID)
REFERENCES NHANVIEN (NhanVienID)
GO
ALTER TABLE NVQUANLI CHECK CONSTRAINT FK_NVQUANLI_NHANVIEN
GO
ALTER TABLE PHONG  WITH CHECK ADD  CONSTRAINT FK_PHONG_LOAIPHONG FOREIGN KEY(LoaiPhongID)
REFERENCES LOAIPHONG (LoaiPhongID)
GO
ALTER TABLE PHONG CHECK CONSTRAINT FK_PHONG_LOAIPHONG
GO
ALTER TABLE NHANVIEN WITH CHECK ADD  CONSTRAINT FK_NHANVIEN_LOAINHANVIEN FOREIGN KEY(Loai)
REFERENCES LOAINHANVIEN(LoaiNVID )
GO
ALTER TABLE NHANVIEN CHECK CONSTRAINT FK_NHANVIEN_LOAINHANVIEN

GO
ALTER TABLE NHANVIEN
ADD AnhDaiDien Image

GO
ALTER TABLE DICHVU
ADD HinhAnh Image

GO
ALTER TABLE THONGTINDANGKI WITH CHECK ADD  CONSTRAINT FK_THONGTINDANGKI_NHANVIEN FOREIGN KEY(NhanVienID)
REFERENCES NHANVIEN(NhanVienID ) 

GO
ALTER TABLE THONGTINDANGKI WITH CHECK ADD  CONSTRAINT FK_THONGTINDANGKI_HASTAG FOREIGN KEY(HastagID)
REFERENCES HASTAG(HastagID)